package maintain

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/afero"
)

const wantAgentsStamp = "<!-- generated by MarkRosemaker/devtool — edit files in AGENTS/ instead. -->"

func TestGenerateAgents(t *testing.T) {
	t.Run("a repository with no fragments still gets the header", func(t *testing.T) {
		got := generateAgentsAndRead(t, afero.NewMemMapFs())

		checkOrder(t, got, []string{
			wantAgentsStamp,
			"## Starting work",
			"## Committing",
			"## Generated files",
			"`AGENTS.md` → `AGENTS/`",
			"## Keeping the documents true",
			"## Code",
			"## Reviews",
		})

		// Nothing to link, so no section inviting anybody to look.
		if strings.Contains(got, "## Particular to this repository") {
			t.Errorf("want no fragment section where there are none:\n%s", got)
		}
	})

	// These are the conventions every repository is held to, so losing one
	// quietly is the failure worth a test of its own: this is the file an
	// agent reads instead of being told.
	t.Run("the conventions an agent has to know are all there", func(t *testing.T) {
		got := generateAgentsAndRead(t, afero.NewMemMapFs())

		for _, want := range []string{
			"Pull `main` and branch from it",
			"`feat/`, `fix/` or `chore/`",
			// Merging deletes the branch, so the next work starts a new one.
			"Merging deletes the branch.",
			"One branch and one pull request at a time",
			"Once you have branched, leave `main` alone",
			// The exit from that rule: a branch that cannot merge is not
			// something to reconcile on your own initiative.
			"say so and stop",
			// One thing at a time is per repository and per conversation,
			// and a second idea rides the open pull request or the roadmap.
			"Not in a second branch.",
			"Watching a pull request costs nothing",
			"`make ready` passes before every commit",
			// What ready regenerates is its output, not a failure to recover
			// from.
			"Because it regenerates, it may leave changes of its own.",
			"`make all` adds `govulncheck`",
			"One commit per piece of work",
			"Push each commit as soon as it is made",
			"Open the pull request yourself",
			"`README/*.md` is the README",
			"`docs/architecture.md` describes the architecture as it stands",
			"Delete an entry when it is done",
			"`mk/*.mk` is where a make target goes",
			"`AGENTS/*.md` is this file's repository-specific half",
			// The feedback loop: an agent that hits a bad instruction is
			// meant to say so, and losing this line loses the loop.
			"and it is meant to improve",
			"Comments are one line",
			"Resolve a thread once you have acted on it",
		} {
			if !strings.Contains(got, want) {
				t.Errorf("the header no longer says %q:\n%s", want, got)
			}
		}
	})

	t.Run("fragments are linked, not embedded", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "AGENTS/conventions.md",
			"# Conventions\n\nThe body of this must not reach AGENTS.md.\n")

		got := generateAgentsAndRead(t, fs)

		if !strings.Contains(got, "- [Conventions](AGENTS/conventions.md)") {
			t.Errorf("missing the link:\n%s", got)
		}

		// The whole point: a file read into every session pays for what it
		// holds, so it holds a line rather than the text.
		if strings.Contains(got, "The body of this must not reach") {
			t.Errorf("the fragment body was embedded:\n%s", got)
		}
	})

	t.Run("a link says the fragment's own heading, or its name", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "AGENTS/titled.md", "# How to do the thing\n\nLike so.\n")
		writeFile(t, fs, "AGENTS/custom_instruction.md", "No heading, just prose.\n")

		got := generateAgentsAndRead(t, fs)

		for _, want := range []string{
			"- [How to do the thing](AGENTS/titled.md)",
			"- [custom_instruction](AGENTS/custom_instruction.md)",
		} {
			if !strings.Contains(got, want) {
				t.Errorf("missing %q:\n%s", want, got)
			}
		}
	})

	// An agent told to edit README/ when the README is somebody's own
	// hand-written file would be told wrong.
	t.Run("only root files that really are generated are named", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, readmePath, "<!-- "+generatedBy+" — edit files in README/ instead. -->\n")
		writeFile(t, fs, makefilePath, "# a Makefile somebody wrote\n\nbuild:\n\techo hi\n")

		got := generateAgentsAndRead(t, fs)

		if !strings.Contains(got, "`README.md` → `README/`") {
			t.Errorf("want the generated README named:\n%s", got)
		}

		if strings.Contains(got, "`Makefile` → `mk/`") {
			t.Errorf("a hand-written Makefile should not be called generated:\n%s", got)
		}
	})

	// A repository whose .gitignore is wholly its own would be told wrong,
	// and a repository whose block exists needs telling where in the file to
	// write, since "edit the directory" has no directory to name here.
	t.Run("the .gitignore block is mentioned only where it exists", func(t *testing.T) {
		// Short enough not to span the wrap in the rendered text.
		const says = "only the marked block at its head"

		bare := afero.NewMemMapFs()
		writeFile(t, bare, gitignorePath, "# wholly mine\n*.out\n")

		if got := generateAgentsAndRead(t, bare); strings.Contains(got, says) {
			t.Errorf("this .gitignore has no block of ours:\n%s", got)
		}

		blocked := afero.NewMemMapFs()
		writeFile(t, blocked, gitignorePath, gitignoreOpen+"\nbin/\n"+gitignoreClose+"\n")

		if got := generateAgentsAndRead(t, blocked); !strings.Contains(got, says) {
			t.Errorf("the block is there and unmentioned:\n%s", got)
		}
	})

	// The go:generate directive is what makes this true rather than
	// api/interactions.json on its own: a repository can have one without
	// the other, and only the directive says openapi-enrich actually runs.
	t.Run("openapi-enrich is mentioned only where it runs", func(t *testing.T) {
		const paragraph = "openapi-enrich"

		t.Run("no interactions file", func(t *testing.T) {
			fs := afero.NewMemMapFs()
			writeFile(t, fs, "main.go",
				"package main\n\n//go:generate go tool openapi-enrich\n\nfunc main() {}\n")

			if got := generateAgentsAndRead(t, fs); strings.Contains(got, paragraph) {
				t.Errorf("no interactions file to enrich from:\n%s", got)
			}
		})

		t.Run("interactions file but no directive", func(t *testing.T) {
			fs := afero.NewMemMapFs()
			writeFile(t, fs, "api/interactions.json", "{}\n")

			if got := generateAgentsAndRead(t, fs); strings.Contains(got, paragraph) {
				t.Errorf("nothing runs openapi-enrich:\n%s", got)
			}
		})

		// go:generate is read from the file it is written in, so a
		// directive elsewhere would not be the one editing the root
		// api/openapi.json.
		t.Run("directive outside the root", func(t *testing.T) {
			fs := afero.NewMemMapFs()
			writeFile(t, fs, "api/interactions.json", "{}\n")
			writeFile(t, fs, "cmd/tool/main.go",
				"package main\n\n//go:generate go tool openapi-enrich\n\nfunc main() {}\n")

			if got := generateAgentsAndRead(t, fs); strings.Contains(got, paragraph) {
				t.Errorf("the directive is not in a root file:\n%s", got)
			}
		})

		t.Run("both present", func(t *testing.T) {
			fs := afero.NewMemMapFs()
			writeFile(t, fs, "api/interactions.json", "{}\n")
			writeFile(t, fs, "main.go",
				"package main\n\n//go:generate go tool openapi-enrich -out api/openapi.json\n\n"+
					"func main() {}\n")

			got := generateAgentsAndRead(t, fs)

			for _, want := range []string{
				"`api/openapi.json` is partly generated",
				"read the diff of `api/openapi.json`",
			} {
				if !strings.Contains(got, want) {
					t.Errorf("missing %q:\n%s", want, got)
				}
			}

			// No frontend/ here, so nothing about mock data.
			if strings.Contains(got, "mock data") {
				t.Errorf("no frontend/, want no mention of it:\n%s", got)
			}
		})
	})

	// Condition B rides on condition A: a frontend/ directory says nothing
	// on its own about interactions.json being anybody's mock data.
	t.Run("the frontend paragraph needs openapi-enrich too", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "frontend/mocks.json", "{}\n")

		if got := generateAgentsAndRead(t, fs); strings.Contains(got, "mock data") {
			t.Errorf("no openapi-enrich, want no mention of the frontend:\n%s", got)
		}
	})

	t.Run("both conditions together get both paragraphs", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "api/interactions.json", "{}\n")
		writeFile(t, fs, "main.go",
			"package main\n\n//go:generate go tool openapi-enrich\n\nfunc main() {}\n")
		writeFile(t, fs, "frontend/mocks.json", "{}\n")

		got := generateAgentsAndRead(t, fs)

		for _, want := range []string{
			"`api/openapi.json` is partly generated",
			"is also the frontend's mock data",
			"`frontend/mocks.json`",
		} {
			if !strings.Contains(got, want) {
				t.Errorf("missing %q:\n%s", want, got)
			}
		}
	})

	t.Run("an existing AGENTS.md is adopted and linked, not overwritten", func(t *testing.T) {
		fs := afero.NewMemMapFs()

		const handWritten = "# House rules\n\nRun the tests.\n"
		writeFile(t, fs, agentsPath, handWritten)

		got := generateAgentsAndRead(t, fs)

		if kept := readFile(t, fs, "AGENTS/legacy.md"); kept != handWritten {
			t.Errorf("AGENTS/legacy.md = %q, want the original verbatim", kept)
		}

		if !strings.Contains(got, "- [House rules](AGENTS/legacy.md)") {
			t.Errorf("the adopted file should be linked:\n%s", got)
		}
	})

	t.Run("an AGENTS.md this task wrote is rewritten, not adopted again", func(t *testing.T) {
		fs := afero.NewMemMapFs()

		first := generateAgentsAndRead(t, fs)
		second := generateAgentsAndRead(t, fs)

		if first != second {
			t.Errorf("output changed between runs:\nfirst:  %q\nsecond: %q", first, second)
		}

		if exists, err := afero.Exists(fs, "AGENTS/legacy.md"); err != nil {
			t.Fatal(err)
		} else if exists {
			t.Error("a generated AGENTS.md was adopted as though it were somebody's own")
		}
	})

	t.Run("an existing AGENTS.md with nowhere to go is an error, not a loss", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, agentsPath, "# House rules\n")
		writeFile(t, fs, "AGENTS/legacy.md", "something else already here\n")

		err := generateAgents(fs)
		if err == nil {
			t.Fatal("expected an error rather than either file being overwritten")
		}

		for _, want := range []string{agentsPath, "AGENTS/legacy.md"} {
			if !strings.Contains(err.Error(), want) {
				t.Errorf("error does not name %q: %v", want, err)
			}
		}
	})

	t.Run("an entry that is not a fragment is an error", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "AGENTS/notes.txt", "not markdown\n")

		if err := generateAgents(fs); err == nil {
			t.Fatal("expected an error for a file that is not a fragment, got nil")
		}
	})

	t.Run("a dotfile is passed over", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "AGENTS/.keep", "")

		if got := generateAgentsAndRead(t, fs); strings.Contains(got, ".keep") {
			t.Errorf("a dotfile should not be linked:\n%s", got)
		}
	})

	t.Run("non-UTF-8 content is rejected", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		if err := afero.WriteFile(fs, "AGENTS/x.md", []byte{0xff, 0xfe, 0x00}, 0o644); err != nil {
			t.Fatal(err)
		}

		if err := generateAgents(fs); err == nil {
			t.Fatal("expected an error for non-UTF-8 fragment content, got nil")
		}
	})
}

func TestFragmentTitle(t *testing.T) {
	for _, tc := range []struct {
		name, file, content, want string
	}{
		{"a heading", "x.md", "# Conventions\n\nprose\n", "Conventions"},
		{"the first of several", "x.md", "# First\n\n# Second\n", "First"},
		{"a heading further down", "x.md", "prose\n\n# Later\n", "Later"},
		{"no heading", "custom_instruction.md", "just prose\n", "custom_instruction"},
		// "##" is a section inside the fragment, not its title.
		{"only a subheading", "x.md", "## Section\n", "x"},
		{"trailing spaces trimmed", "x.md", "#   Padded   \n", "Padded"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if got := fragmentTitle(tc.file, []byte(tc.content)); got != tc.want {
				t.Errorf("fragmentTitle(%q, %q) = %q, want %q", tc.file, tc.content, got, tc.want)
			}
		})
	}
}

// TestAgentsGolden renders AGENTS.md against golden files, so a change to
// what every agent session reads is a reviewable diff. Run
// "go test ./maintain -update" to rewrite them.
func TestAgentsGolden(t *testing.T) {
	for _, tc := range []struct {
		name string
		data agentsData
	}{
		{"bare", agentsData{Generated: generatedRootDirs[:1]}},
		{"full", agentsData{
			Generated: generatedRootDirs,
			Gitignore: true,
			Fragments: []agentsFragment{
				{Title: "Conventions", Path: "AGENTS/conventions.md"},
				{Title: "custom_instruction", Path: "AGENTS/custom_instruction.md"},
			},
		}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got, err := renderAgents(tc.data)
			if err != nil {
				t.Fatal(err)
			}

			golden := filepath.Join("testdata", "AGENTS."+tc.name+".golden")

			if *update {
				if err := os.WriteFile(golden, got, 0o644); err != nil {
					t.Fatal(err)
				}

				return
			}

			want, err := os.ReadFile(golden)
			if err != nil {
				t.Fatalf("%v (run: go test ./maintain -update)", err)
			}

			if string(got) != string(want) {
				t.Errorf("%s does not match:\n--- got ---\n%s\n--- want ---\n%s", golden, got, want)
			}
		})
	}
}

// TestHasOpenAPIEnrichDirective: a suffix after the tool name, such as an
// -out flag, must not disqualify the line — that is how the directive is
// actually written, to name where it writes.
func TestHasOpenAPIEnrichDirective(t *testing.T) {
	for _, tc := range []struct {
		name string
		main string
		want bool
	}{
		{"bare directive", "//go:generate go tool openapi-enrich\n", true},
		{"with an -out flag", "//go:generate go tool openapi-enrich -out api/openapi.json\n", true},
		{"indented, not a directive make would run", "\t//go:generate go tool openapi-enrich\n", false},
		{"a different tool", "//go:generate go tool other-thing\n", false},
		{"no directive at all", "", false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			fs := afero.NewMemMapFs()
			writeFile(t, fs, "api/interactions.json", "{}\n")
			writeFile(t, fs, "main.go", "package main\n\n"+tc.main+"\nfunc main() {}\n")

			got, err := hasOpenAPIEnrich(fs)
			if err != nil {
				t.Fatal(err)
			}

			if got != tc.want {
				t.Errorf("hasOpenAPIEnrich() = %v, want %v", got, tc.want)
			}
		})
	}
}

func generateAgentsAndRead(t *testing.T, fs afero.Fs) string {
	t.Helper()

	if err := generateAgents(fs); err != nil {
		t.Fatal(err)
	}

	return readFile(t, fs, agentsPath)
}
