package maintain

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/afero"
)

const wantAgentsStamp = "<!-- generated by MarkRosemaker/portfolio — edit files in AGENTS/ instead. -->"

func TestGenerateAgents(t *testing.T) {
	t.Run("a repository with no fragments still gets the header", func(t *testing.T) {
		got := generateAgentsAndRead(t, afero.NewMemMapFs())

		checkOrder(t, got, []string{
			wantAgentsStamp,
			"## Starting work",
			"## Committing",
			"## Generated files",
			"`AGENTS.md` → `AGENTS/`",
			"## Keeping the documents true",
			"## Code",
			"## Reviews",
		})

		// Nothing to link, so no section inviting anybody to look.
		if strings.Contains(got, "## Particular to this repository") {
			t.Errorf("want no fragment section where there are none:\n%s", got)
		}
	})

	// These are the conventions every repository is held to, so losing one
	// quietly is the failure worth a test of its own: this is the file an
	// agent reads instead of being told.
	t.Run("the conventions an agent has to know are all there", func(t *testing.T) {
		got := generateAgentsAndRead(t, afero.NewMemMapFs())

		for _, want := range []string{
			"Pull `main` and branch from it",
			"One branch and one pull request at a time",
			"Once you have branched, leave `main` alone",
			"Watching a pull request costs nothing",
			"`make ci` passes before every commit",
			"`make` runs `ci` plus the checks that need the network",
			"One commit per piece of work",
			"Push each commit as soon as it is made",
			"Open the pull request yourself",
			"`README/*.md` is the README",
			"`docs/architecture.md` describes the architecture as it stands",
			"Delete an entry when it is done",
			"`mk/*.mk` is where a make target goes",
			"`AGENTS/*.md` is this file's repository-specific half",
			// The feedback loop: an agent that hits a bad instruction is
			// meant to say so, and losing this line loses the loop.
			"and it is meant to improve",
			"Comments are one line",
			"Resolve a thread once you have acted on it",
		} {
			if !strings.Contains(got, want) {
				t.Errorf("the header no longer says %q:\n%s", want, got)
			}
		}
	})

	t.Run("fragments are linked, not embedded", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "AGENTS/conventions.md",
			"# Conventions\n\nThe body of this must not reach AGENTS.md.\n")

		got := generateAgentsAndRead(t, fs)

		if !strings.Contains(got, "- [Conventions](AGENTS/conventions.md)") {
			t.Errorf("missing the link:\n%s", got)
		}

		// The whole point: a file read into every session pays for what it
		// holds, so it holds a line rather than the text.
		if strings.Contains(got, "The body of this must not reach") {
			t.Errorf("the fragment body was embedded:\n%s", got)
		}
	})

	t.Run("a link says the fragment's own heading, or its name", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "AGENTS/titled.md", "# How to do the thing\n\nLike so.\n")
		writeFile(t, fs, "AGENTS/custom_instruction.md", "No heading, just prose.\n")

		got := generateAgentsAndRead(t, fs)

		for _, want := range []string{
			"- [How to do the thing](AGENTS/titled.md)",
			"- [custom_instruction](AGENTS/custom_instruction.md)",
		} {
			if !strings.Contains(got, want) {
				t.Errorf("missing %q:\n%s", want, got)
			}
		}
	})

	// An agent told to edit README/ when the README is somebody's own
	// hand-written file would be told wrong.
	t.Run("only root files that really are generated are named", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, readmePath, "<!-- "+generatedMarker+" — edit files in README/ instead. -->\n")
		writeFile(t, fs, makefilePath, "# a Makefile somebody wrote\n\nbuild:\n\techo hi\n")

		got := generateAgentsAndRead(t, fs)

		if !strings.Contains(got, "`README.md` → `README/`") {
			t.Errorf("want the generated README named:\n%s", got)
		}

		if strings.Contains(got, "`Makefile` → `mk/`") {
			t.Errorf("a hand-written Makefile should not be called generated:\n%s", got)
		}
	})

	// A repository whose .gitignore is wholly its own would be told wrong,
	// and a repository whose block exists needs telling where in the file to
	// write, since "edit the directory" has no directory to name here.
	t.Run("the .gitignore block is mentioned only where it exists", func(t *testing.T) {
		// Short enough not to span the wrap in the rendered text.
		const says = "only the marked block at its head"

		bare := afero.NewMemMapFs()
		writeFile(t, bare, gitignorePath, "# wholly mine\n*.out\n")

		if got := generateAgentsAndRead(t, bare); strings.Contains(got, says) {
			t.Errorf("this .gitignore has no block of ours:\n%s", got)
		}

		blocked := afero.NewMemMapFs()
		writeFile(t, blocked, gitignorePath, gitignoreOpen+"\nbin/\n"+gitignoreClose+"\n")

		if got := generateAgentsAndRead(t, blocked); !strings.Contains(got, says) {
			t.Errorf("the block is there and unmentioned:\n%s", got)
		}
	})

	t.Run("an existing AGENTS.md is adopted and linked, not overwritten", func(t *testing.T) {
		fs := afero.NewMemMapFs()

		const handWritten = "# House rules\n\nRun the tests.\n"
		writeFile(t, fs, agentsPath, handWritten)

		got := generateAgentsAndRead(t, fs)

		if kept := readFile(t, fs, "AGENTS/legacy.md"); kept != handWritten {
			t.Errorf("AGENTS/legacy.md = %q, want the original verbatim", kept)
		}

		if !strings.Contains(got, "- [House rules](AGENTS/legacy.md)") {
			t.Errorf("the adopted file should be linked:\n%s", got)
		}
	})

	t.Run("an AGENTS.md this task wrote is rewritten, not adopted again", func(t *testing.T) {
		fs := afero.NewMemMapFs()

		first := generateAgentsAndRead(t, fs)
		second := generateAgentsAndRead(t, fs)

		if first != second {
			t.Errorf("output changed between runs:\nfirst:  %q\nsecond: %q", first, second)
		}

		if exists, err := afero.Exists(fs, "AGENTS/legacy.md"); err != nil {
			t.Fatal(err)
		} else if exists {
			t.Error("a generated AGENTS.md was adopted as though it were somebody's own")
		}
	})

	t.Run("an existing AGENTS.md with nowhere to go is an error, not a loss", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, agentsPath, "# House rules\n")
		writeFile(t, fs, "AGENTS/legacy.md", "something else already here\n")

		err := generateAgents(fs)
		if err == nil {
			t.Fatal("expected an error rather than either file being overwritten")
		}

		for _, want := range []string{agentsPath, "AGENTS/legacy.md"} {
			if !strings.Contains(err.Error(), want) {
				t.Errorf("error does not name %q: %v", want, err)
			}
		}
	})

	t.Run("an entry that is not a fragment is an error", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "AGENTS/notes.txt", "not markdown\n")

		if err := generateAgents(fs); err == nil {
			t.Fatal("expected an error for a file that is not a fragment, got nil")
		}
	})

	t.Run("a dotfile is passed over", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "AGENTS/.keep", "")

		if got := generateAgentsAndRead(t, fs); strings.Contains(got, ".keep") {
			t.Errorf("a dotfile should not be linked:\n%s", got)
		}
	})

	t.Run("non-UTF-8 content is rejected", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		if err := afero.WriteFile(fs, "AGENTS/x.md", []byte{0xff, 0xfe, 0x00}, 0o644); err != nil {
			t.Fatal(err)
		}

		if err := generateAgents(fs); err == nil {
			t.Fatal("expected an error for non-UTF-8 fragment content, got nil")
		}
	})
}

func TestFragmentTitle(t *testing.T) {
	for _, tc := range []struct {
		name, file, content, want string
	}{
		{"a heading", "x.md", "# Conventions\n\nprose\n", "Conventions"},
		{"the first of several", "x.md", "# First\n\n# Second\n", "First"},
		{"a heading further down", "x.md", "prose\n\n# Later\n", "Later"},
		{"no heading", "custom_instruction.md", "just prose\n", "custom_instruction"},
		// "##" is a section inside the fragment, not its title.
		{"only a subheading", "x.md", "## Section\n", "x"},
		{"trailing spaces trimmed", "x.md", "#   Padded   \n", "Padded"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if got := fragmentTitle(tc.file, []byte(tc.content)); got != tc.want {
				t.Errorf("fragmentTitle(%q, %q) = %q, want %q", tc.file, tc.content, got, tc.want)
			}
		})
	}
}

// TestAgentsGolden renders AGENTS.md against golden files, so a change to
// what every agent session reads is a reviewable diff. Run
// "go test ./maintain -update" to rewrite them.
func TestAgentsGolden(t *testing.T) {
	for _, tc := range []struct {
		name string
		data agentsData
	}{
		{"bare", agentsData{Generated: generatedRootDirs[:1]}},
		{"full", agentsData{
			Generated: generatedRootDirs,
			Gitignore: true,
			Fragments: []agentsFragment{
				{Title: "Conventions", Path: "AGENTS/conventions.md"},
				{Title: "custom_instruction", Path: "AGENTS/custom_instruction.md"},
			},
		}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got, err := renderAgents(tc.data)
			if err != nil {
				t.Fatal(err)
			}

			golden := filepath.Join("testdata", "AGENTS."+tc.name+".golden")

			if *update {
				if err := os.WriteFile(golden, got, 0o644); err != nil {
					t.Fatal(err)
				}

				return
			}

			want, err := os.ReadFile(golden)
			if err != nil {
				t.Fatalf("%v (run: go test ./maintain -update)", err)
			}

			if string(got) != string(want) {
				t.Errorf("%s does not match:\n--- got ---\n%s\n--- want ---\n%s", golden, got, want)
			}
		})
	}
}

func generateAgentsAndRead(t *testing.T, fs afero.Fs) string {
	t.Helper()

	if err := generateAgents(fs); err != nil {
		t.Fatal(err)
	}

	return readFile(t, fs, agentsPath)
}
