package maintain

import (
	"bytes"
	"context"
	_ "embed"
	"errors"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"

	engine "github.com/MarkRosemaker/devtool-engine/maintain"
	"github.com/spf13/afero"
	"github.com/sqlc-dev/sqlc/pkg/cli"
	"golang.org/x/mod/modfile"
)

// databasesDir holds one directory per declared database.
const databasesDir = "databases"

var (
	//go:embed migrate.go.tmpl
	migrateText string

	//go:embed queries_test.go.tmpl
	queriesTestText string

	migrateTmpl     = template.Must(template.New("migrate.go").Parse(migrateText))
	queriesTestTmpl = template.Must(template.New("queries_test.go").Parse(queriesTestText))
)

// sqlcHeader opens every file sqlc writes, which is how a file it wrote for a
// query file since deleted is told apart from a person's.
const sqlcHeader = "// Code generated by sqlc. DO NOT EDIT."

// GenerateQueries runs sqlc over the database name of the repository in dir,
// returning sqlc's exit code. Its errors go to stderr.
//
// sqlc reads its configuration only from a file, so one is written for the
// run outside the repository: a repository declares its databases in
// devtool.json and holds no sqlc.yaml. The paths in it are relative because
// sqlc joins every path onto the file's directory, absolute ones included.
func GenerateQueries(dir, name string) int {
	tmp, err := os.MkdirTemp("", "devtool-sqlc")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)

		return 1
	}
	defer func() { _ = os.RemoveAll(tmp) }()

	db, err := filepath.Rel(tmp, filepath.Join(dir, databasesDir, name))
	if err != nil {
		fmt.Fprintln(os.Stderr, err)

		return 1
	}

	db = filepath.ToSlash(db)
	config := fmt.Sprintf(`version: "2"
sql:
  - engine: sqlite
    schema: %q
    queries: %q
    gen:
      go:
        package: %q
        out: %q
`, db+"/migrations", db+"/queries", name, db)

	file := filepath.Join(tmp, "sqlc.yaml")
	if err := os.WriteFile(file, []byte(config), 0o600); err != nil {
		fmt.Fprintln(os.Stderr, err)

		return 1
	}

	return cli.Run([]string{"generate", "-f", file})
}

// SQLC runs sqlc over one of repo's databases. [RunSQLC] is the one a run
// uses; a test that cannot start devtool runs [GenerateQueries] in-process.
type SQLC func(ctx context.Context, repo engine.Repo, name string) error

// RunSQLC runs sqlc as a child of this devtool, "devtool sqlc <name>" in the
// repository's directory.
//
// A child rather than a call: sqlc writes its errors to the process's own
// stderr and exits the process on some of them, and a run maintains
// repositories side by side. In a child, its errors become this one's.
func RunSQLC(ctx context.Context, repo engine.Repo, name string) error {
	self, err := os.Executable()
	if err != nil {
		return err
	}

	if out, err := repo.ExecCommand(ctx, self, "sqlc", name); err != nil {
		if out = bytes.TrimSpace(out); len(out) > 0 {
			return fmt.Errorf("%w: %s", err, out)
		}

		return err
	}

	return nil
}

// DatabasesTask generates the code for the databases the repository declares
// in devtool.json. A database named foo lives in databases/foo, package foo:
//
//	migrations/<version>_<title>.up.sql   the schema, the first one its initial state
//	queries/*.sql                         sqlc queries
//
// From those it writes sqlc's code, migrate.go — the migrations embedded,
// and Migrate to apply them — and queries_test.go, which prepares every
// query against the migrated schema.
func DatabasesTask(repo engine.Repo, sqlc SQLC) engine.Task {
	return engine.Task{
		Name:  "databases",
		Short: "databases",
		Run: func(ctx context.Context) error {
			def, _, err := LoadDefinition(repo.Fs())
			if err != nil {
				return err
			}

			for _, db := range def.Resources.Databases {
				if err := generateDatabase(ctx, repo, sqlc, db.Name); err != nil {
					return fmt.Errorf("database %q: %w", db.Name, err)
				}
			}

			return nil
		},
	}
}

var databaseName = regexp.MustCompile(`^[a-z][a-z0-9]*$`)

func generateDatabase(ctx context.Context, repo engine.Repo, sqlc SQLC, name string) error {
	// The name is the package's, and the directory's.
	if !databaseName.MatchString(name) {
		return errors.New("a database's name has to be lower-case letters and digits, " +
			"starting with a letter, since it names the package")
	}

	fs, dir := repo.Fs(), path.Join(databasesDir, name)

	// Caught here rather than by go:embed, whose complaint about a pattern
	// matching nothing says nothing about what to add.
	if up, err := afero.Glob(fs, path.Join(dir, "migrations", "*.up.sql")); err != nil {
		return err
	} else if len(up) == 0 {
		return fmt.Errorf("%s has no migrations: add %s/migrations/001_initial.up.sql, "+
			"which creates the schema", dir, dir)
	}

	if err := removeGenerated(fs, dir); err != nil {
		return err
	}

	if err := sqlc(ctx, repo, name); err != nil {
		return fmt.Errorf("sqlc: %w", err)
	}

	if err := writeTemplate(fs, path.Join(dir, "migrate.go"), migrateTmpl,
		struct{ Package string }{name}); err != nil {
		return err
	}

	return writeQueriesTest(fs, dir, name)
}

// removeGenerated deletes what sqlc wrote last time, which it never does
// itself: the code for a query file that has since gone would stay.
func removeGenerated(fs afero.Fs, dir string) error {
	entries, err := afero.ReadDir(fs, dir)
	if err != nil {
		return fmt.Errorf("reading %s: %w", dir, err)
	}

	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
			continue
		}

		file := path.Join(dir, e.Name())

		b, err := afero.ReadFile(fs, file)
		if err != nil {
			return err
		}

		if bytes.HasPrefix(b, []byte(sqlcHeader)) {
			if err := fs.Remove(file); err != nil {
				return err
			}
		}
	}

	return nil
}

// queryConst finds the constants sqlc writes a query into.
var queryConst = regexp.MustCompile("(?m)^const (\\w+) = `-- name: ")

// writeQueriesTest writes the test that prepares every query, or removes it
// where there is nothing to prepare.
func writeQueriesTest(fs afero.Fs, dir, name string) error {
	file := path.Join(dir, "queries_test.go")

	queries, err := generatedQueries(fs, dir)
	if err != nil {
		return err
	}

	if len(queries) == 0 {
		if err := fs.Remove(file); err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}

		return nil
	}

	driver, imports, err := sqliteDriver(fs)
	if err != nil {
		return err
	}

	return writeTemplate(fs, file, queriesTestTmpl, struct {
		Package, Driver  string
		Imports, Queries []string
	}{name, driver, imports, queries})
}

func generatedQueries(fs afero.Fs, dir string) ([]string, error) {
	files, err := afero.Glob(fs, path.Join(dir, "*.sql.go"))
	if err != nil {
		return nil, err
	}

	var queries []string

	for _, f := range files {
		b, err := afero.ReadFile(fs, f)
		if err != nil {
			return nil, err
		}

		for _, m := range queryConst.FindAllSubmatch(b, -1) {
			queries = append(queries, string(m[1]))
		}
	}

	return queries, nil
}

// sqliteDrivers are the database/sql drivers the generated test knows, by
// module: the name each registers, and what has to be imported for it.
var sqliteDrivers = []struct {
	module, driver string
	imports        []string
}{
	{"modernc.org/sqlite", "sqlite", []string{"modernc.org/sqlite"}},
	{"github.com/ncruces/go-sqlite3", "sqlite3", []string{
		"github.com/ncruces/go-sqlite3/driver",
		"github.com/ncruces/go-sqlite3/embed",
	}},
}

// sqliteDriver picks the driver the repository already requires, so the
// generated test adds no dependency of its own.
func sqliteDriver(fs afero.Fs) (string, []string, error) {
	b, err := afero.ReadFile(fs, "go.mod")
	if err != nil {
		return "", nil, err
	}

	mod, err := modfile.ParseLax("go.mod", b, nil)
	if err != nil {
		return "", nil, err
	}

	for _, d := range sqliteDrivers {
		for _, r := range mod.Require {
			if r.Mod.Path == d.module {
				return d.driver, d.imports, nil
			}
		}
	}

	return "", nil, fmt.Errorf("go.mod requires no SQLite driver to test the queries with; "+
		"add %s or %s", sqliteDrivers[0].module, sqliteDrivers[1].module)
}

func writeTemplate(fs afero.Fs, file string, tmpl *template.Template, data any) error {
	buf := &bytes.Buffer{}
	if err := tmpl.Execute(buf, data); err != nil {
		return fmt.Errorf("rendering %s: %w", file, err)
	}

	return afero.WriteFile(fs, file, buf.Bytes(), 0o644)
}
