// Package maintain holds the generators this owner applies to every
// repository in the portfolio.
//
// The machinery they plug into — the task, the repository interface and the
// runner that applies a sequence of them — lives in
// github.com/MarkRosemaker/devtool-engine. What is here is the half nobody
// else would want unchanged: a README fragment schema, a Makefile shape, a
// set of .gitignore rules, and an AGENTS.md whose template is a particular
// set of working conventions written out as prose.
package maintain

// generatedMarker is on the first line of every file this package writes,
// whatever that file's comment syntax, so one can be told from a
// hand-written one.
//
// It still names portfolio, which no longer generates anything. Renaming it is
// not a rename: the marker is also how an existing file is recognised as this
// tool's own, so a new one would make every file already out there read as
// hand-written and be adopted rather than regenerated. Changing it means
// writing the new marker while matching both, which is its own change.
const generatedMarker = "generated by MarkRosemaker/portfolio"
