// Package maintain holds the generators this owner applies to every
// repository in the portfolio.
//
// The machinery they plug into — the task, the repository interface and the
// runner that applies a sequence of them — lives in
// github.com/MarkRosemaker/devtool-engine. What is here is the half nobody
// else would want unchanged: a README fragment schema, a Makefile shape, a
// set of .gitignore rules, and an AGENTS.md whose template is a particular
// set of working conventions written out as prose.
package maintain

import "regexp"

// generatedBy is written on the first line of every file this package writes,
// whatever that file's comment syntax, so one can be told from a hand-written
// one.
const generatedBy = "generated by MarkRosemaker/devtool"

// generatedMarker matches that line whichever tool wrote it, which is what
// lets the name change without every file already out there reading as
// hand-written and being adopted rather than regenerated.
//
// Go's own convention is the same shape — a fixed sentence around a free
// middle, "^// Code generated .* DO NOT EDIT\.$" — and for the same reason:
// what identifies a generated file is the wording, not who did the
// generating. The comment opener is part of it, since that is what separates
// a marker from a sentence of prose that happens to say the words.
var generatedMarker = regexp.MustCompile(`^\s*(#|<!--)\s*generated by \S+`)
