package maintain

import (
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/spf13/afero"
)

// wantMakefileStamp is the generated-file marker spelled out, rather than
// read from the code under test, which could not then notice it changing.
const wantMakefileStamp = "# generated by MarkRosemaker/portfolio — edit files in mk/ instead."

func TestGenerateMakefile(t *testing.T) {
	t.Run("a repository with nothing of its own gets the house targets", func(t *testing.T) {
		fs := afero.NewMemMapFs()

		if err := generateMakefile(fs, false); err != nil {
			t.Fatal(err)
		}

		got := readFile(t, fs, makefilePath)

		checkOrder(t, got, []string{
			wantMakefileStamp,
			// The default goal has to be set before the include, or a
			// fragment could take it just by declaring a target first.
			".DEFAULT_GOAL := all",
			".DELETE_ON_ERROR:",
			"all: ci vuln",
			"ci: fix verify vet test-race",
			"lint:", "golangci-lint run",
			"test:", "go test ./...",
			"generate:", "go generate ./...",
		})

		// Nothing in mk/, so nothing to include: a generated file should
		// carry no include for a file that is not there.
		if strings.Contains(got, "include") {
			t.Errorf("want no include line at all:\n%s", got)
		}
	})

	t.Run("a target a fragment defines is left to the fragment", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "mk/repo.mk", "test:\n\tgo test -race ./...\n")

		if err := generateMakefile(fs, false); err != nil {
			t.Fatal(err)
		}

		got := readFile(t, fs, makefilePath)

		// Defining it here too would work — the later definition wins — but
		// make would warn about the overridden recipe on every invocation.
		if strings.Contains(got, "go test ./...") {
			t.Errorf("the house recipe should have been left out:\n%s", got)
		}

		if strings.Contains(got, ".PHONY: all lint test generate") {
			t.Errorf("a target left to the fragment should not be declared phony here:\n%s", got)
		}

		// The ones it did not define are still there, and all still depends
		// on the name whichever version defines it.
		checkOrder(t, got, []string{"all: ci vuln", "lint:", "generate:"})
	})

	t.Run("an existing Makefile is adopted, not overwritten", func(t *testing.T) {
		fs := afero.NewMemMapFs()

		const handWritten = "build:\n\t@echo building\n\ntest:\n\t@echo testing\n"
		writeFile(t, fs, makefilePath, handWritten)

		if err := generateMakefile(fs, false); err != nil {
			t.Fatal(err)
		}

		if got := readFile(t, fs, "mk/legacy.mk"); got != handWritten {
			t.Errorf("mk/legacy.mk = %q, want the original Makefile verbatim", got)
		}

		got := readFile(t, fs, makefilePath)

		// Plain "make" has to go on meaning what it meant, so the adopted
		// file's own first target stays the default.
		if !strings.Contains(got, ".DEFAULT_GOAL := build") {
			t.Errorf("the adopted default goal was not kept:\n%s", got)
		}

		if strings.Contains(got, "go test ./...") {
			t.Errorf("the adopted test target should not be defined twice:\n%s", got)
		}
	})

	t.Run("a Makefile this task wrote is rewritten, not adopted again", func(t *testing.T) {
		fs := afero.NewMemMapFs()

		if err := generateMakefile(fs, false); err != nil {
			t.Fatal(err)
		}

		first := readFile(t, fs, makefilePath)

		if err := generateMakefile(fs, false); err != nil {
			t.Fatal(err)
		}

		if second := readFile(t, fs, makefilePath); first != second {
			t.Errorf("output changed between runs:\nfirst:  %q\nsecond: %q", first, second)
		}

		if exists, err := afero.Exists(fs, "mk/legacy.mk"); err != nil {
			t.Fatal(err)
		} else if exists {
			t.Error("a generated Makefile was adopted as though it were somebody's own")
		}
	})

	// Only this task ever writes mk/legacy.mk, which is what makes taking
	// the default goal from it safe. A fragment a human wrote must not
	// change what plain "make" runs just by being there.
	t.Run("a fragment of the repository's own does not take the default goal", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "mk/repo.mk", "deploy:\n\t@echo deploying\n")

		if err := generateMakefile(fs, false); err != nil {
			t.Fatal(err)
		}

		if got := readFile(t, fs, makefilePath); !strings.Contains(got, ".DEFAULT_GOAL := all") {
			t.Errorf("want the default goal left alone:\n%s", got)
		}
	})

	t.Run("an existing Makefile with nowhere to go is an error, not a loss", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, makefilePath, "build:\n\t@echo building\n")
		writeFile(t, fs, "mk/legacy.mk", "something else already here\n")

		err := generateMakefile(fs, false)
		if err == nil {
			t.Fatal("expected an error rather than either file being overwritten")
		}

		for _, want := range []string{makefilePath, "mk/legacy.mk"} {
			if !strings.Contains(err.Error(), want) {
				t.Errorf("error does not name %q: %v", want, err)
			}
		}
	})

	t.Run("an entry make would never include is an error", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "mk/notes.txt", "make ignores this entirely\n")

		err := generateMakefile(fs, false)
		if err == nil {
			t.Fatal("expected an error for a file that would never be included, got nil")
		}

		if !strings.Contains(err.Error(), "mk/notes.txt") {
			t.Errorf("error does not name the file: %v", err)
		}
	})

	t.Run("a dotfile is passed over", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "mk/.keep", "")

		if err := generateMakefile(fs, false); err != nil {
			t.Fatal(err)
		}
	})

	t.Run("non-UTF-8 content is rejected", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		if err := afero.WriteFile(fs, "mk/repo.mk", []byte{0xff, 0xfe, 0x00}, 0o644); err != nil {
			t.Fatal(err)
		}

		if err := generateMakefile(fs, false); err == nil {
			t.Fatal("expected an error for non-UTF-8 fragment content, got nil")
		}
	})
}

func TestMakeTargets(t *testing.T) {
	for _, tc := range []struct {
		name, fragment string
		want           []string
	}{
		{"a plain target", "build:\n\techo hi\n", []string{"build"}},
		{"prerequisites", "all: lint test\n", []string{"all"}},
		{"a double-colon rule", "clean::\n\trm -rf out\n", []string{"clean"}},
		{"several, in order", "b:\n\techo\n\na:\n\techo\n", []string{"b", "a"}},
		{"named once, however often defined", "b:\n\techo\nb: extra\n", []string{"b"}},
		// Assignments are not targets, however much they look like one.
		{"a simple assignment", "GO := go\n", nil},
		{"an expanded assignment", "GO ::= go\n", nil},
		{"a conditional assignment", "GO ?= go\n", nil},
		// A recipe line is indented, so what it contains is the shell's.
		{"a colon inside a recipe", "build:\n\tssh host:/path\n", []string{"build"}},
		// make's own special targets are not something to ask for by name.
		{"a special target", ".PHONY: test\n", nil},
		{"a comment", "# build: not a target\n", nil},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got := makeTargets([]byte(tc.fragment))

			if strings.Join(got, ",") != strings.Join(tc.want, ",") {
				t.Errorf("makeTargets(%q) = %v, want %v", tc.fragment, got, tc.want)
			}
		})
	}
}

// TestGenerateMakefileRunsUnderMake checks the generated file against the
// program that has to read it. Everything else here asserts about text;
// this asserts that make agrees — that the default goal survives adoption,
// that a fragment's target is reachable from the root, and that nothing
// provokes the "overriding recipe" warning that defining a target twice
// would.
func TestGenerateMakefileRunsUnderMake(t *testing.T) {
	if _, err := exec.LookPath("make"); err != nil {
		t.Skip("make is not installed")
	}

	dir := t.TempDir()
	fs := afero.NewBasePathFs(afero.NewOsFs(), dir)

	// A repository as it would be found: its own Makefile, defaulting to a
	// target of its own, and defining one of the house names differently.
	writeFile(t, fs, makefilePath,
		"build:\n\t@echo built\n\ntest:\n\t@echo repo-test\n\nship: build\n\t@echo shipped\n")

	if err := generateMakefile(fs, false); err != nil {
		t.Fatal(err)
	}

	for _, tc := range []struct {
		name string
		args []string
		want string
	}{
		{"plain make runs what it used to", nil, "built"},
		{"a target of the repository's own is reachable", []string{"ship"}, "shipped"},
		{"the repository's version of a house name wins", []string{"test"}, "repo-test"},
		{"a house target the repository left alone is there", []string{"-n", "generate"}, "go generate ./..."},
	} {
		t.Run(tc.name, func(t *testing.T) {
			cmd := exec.CommandContext(t.Context(), "make", tc.args...)
			cmd.Dir = dir

			out, err := cmd.CombinedOutput()
			if err != nil {
				t.Fatalf("make %v: %v\n%s", tc.args, err, out)
			}

			if !strings.Contains(string(out), tc.want) {
				t.Errorf("make %v printed %q, want it to contain %q", tc.args, out, tc.want)
			}

			// Defining a target twice is legal and make only warns, which
			// is exactly why it is worth failing on: nobody reads a warning
			// printed on every build.
			if strings.Contains(string(out), "overriding recipe") {
				t.Errorf("make warned about an overridden recipe:\n%s", out)
			}
		})
	}
}

// TestMakefileGolden renders the generated Makefile against golden files,
// so a change to it is a reviewable diff. Run "go test ./maintain -update"
// to rewrite them.
func TestMakefileGolden(t *testing.T) {
	for _, tc := range []struct {
		name string
		data makefileData
	}{
		{"house", makefileData{
			DefaultGoal: defaultGoal,
			CleanFiles:  coverProfile,
			Tools:       true,
			Targets:     houseTargets(repoShape{}),
		}},
		{"adopted", makefileData{
			DefaultGoal: "build",
			Targets:     slices.Delete(houseTargets(repoShape{}), 2, 3),
		}},
		{"binary", makefileData{
			DefaultGoal: defaultGoal,
			Command:     "worldweaver",
			CleanFiles:  "bin cover.out",
			Tools:       true,
			Targets:     houseTargets(repoShape{Command: "worldweaver", Benchmarks: true}),
			Flags:       "mk/flags.mk",
			Includes:    []string{"mk/legacy.mk", "mk/sprites.mk"},
		}},
		{"none", makefileData{DefaultGoal: "build"}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got, err := renderMakefile(tc.data)
			if err != nil {
				t.Fatal(err)
			}

			golden := filepath.Join("testdata", "Makefile."+tc.name+".golden")

			if *update {
				if err := os.WriteFile(golden, got, 0o644); err != nil {
					t.Fatal(err)
				}

				return
			}

			want, err := os.ReadFile(golden)
			if err != nil {
				t.Fatalf("%v (run: go test ./maintain -update)", err)
			}

			if string(got) != string(want) {
				t.Errorf("%s does not match:\n--- got ---\n%s\n--- want ---\n%s", golden, got, want)
			}
		})
	}
}

// TestGenerateMakefileCommand covers the build target, which a repository
// gets only when there is exactly one thing to build and so no way to pick
// the wrong one.
func TestGenerateMakefileCommand(t *testing.T) {
	for _, tc := range []struct {
		name    string
		cmds    []string
		want    string
		wantNot string
	}{
		{"one command", []string{"worldweaver"}, "bin/worldweaver", ""},
		// Which of two is the binary is anybody's guess, so neither is.
		{"two commands", []string{"worldweaver", "weaverctl"}, "", "BINARY"},
		{"no cmd directory at all", nil, "", "BINARY"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			fs := afero.NewMemMapFs()
			for _, cmd := range tc.cmds {
				writeFile(t, fs, "cmd/"+cmd+"/main.go", "package main\n")
			}

			if err := generateMakefile(fs, false); err != nil {
				t.Fatal(err)
			}

			got := readFile(t, fs, makefilePath)

			if tc.want != "" {
				checkOrder(t, got, []string{
					"BINARY := " + tc.want,
					"PKG    := ./cmd/" + tc.cmds[0] + "/",
					// all builds it, and the recipe goes through the
					// variables so a fragment can repoint either.
					"ci: fix verify vet test-race build",
					"build:", "mkdir -p bin", "go build -o $(BINARY) $(PKG)",
				})
			}

			if tc.wantNot != "" && strings.Contains(got, tc.wantNot) {
				t.Errorf("want no %q in:\n%s", tc.wantNot, got)
			}
		})
	}

	// run drives the binary build produces. Where the repository builds its
	// own, only it knows where that lands — so it owns run as well, rather
	// than getting one that runs $(BINARY) and fails on a path its build
	// never wrote to.
	t.Run("a repository defining build owns run too", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "cmd/worldweaver/main.go", "package main\n")
		writeFile(t, fs, "mk/repo.mk", "build:\n\tgo build -o dist/ww ./cmd/worldweaver\n")

		got := generateAndRead(t, fs)

		for _, unwanted := range []string{"run:", "$(BINARY) $(ARGS)"} {
			if strings.Contains(got, unwanted) {
				t.Errorf("want no %q where the repository builds its own:\n%s", unwanted, got)
			}
		}

		// The rest is unaffected: only what depends on build goes.
		checkOrder(t, got, []string{"lint:", "test:", "format:", "fix:", "generate:"})
	})

	t.Run("a repository defining build keeps its own", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "cmd/worldweaver/main.go", "package main\n")
		writeFile(t, fs, "mk/repo.mk", "build:\n\tgo build -tags prod ./...\n")

		if err := generateMakefile(fs, false); err != nil {
			t.Fatal(err)
		}

		got := readFile(t, fs, makefilePath)

		if strings.Contains(got, "go build -o $(BINARY)") {
			t.Errorf("the house build recipe should have been left out:\n%s", got)
		}

		// The variables are still worth writing: the fragment's recipe may
		// well use them, and defining one twice costs nothing.
		if !strings.Contains(got, "BINARY := bin/worldweaver") {
			t.Errorf("want BINARY defined even where the recipe is the repository's:\n%s", got)
		}
	})
}

// TestGenerateMakefileIncludes covers which include lines the generated
// file carries: mk/flags.mk ahead of everything that might use it, the rest
// at the foot, each named rather than matched, and none at all for a
// fragment that is not there.
func TestGenerateMakefileIncludes(t *testing.T) {
	t.Run("flags first, the rest last, each named", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "mk/flags.mk", "export CGO_CFLAGS := -Wall\n")
		writeFile(t, fs, "mk/repo.mk", "sprite:\n\t@echo sprite\n")

		got := generateAndRead(t, fs)

		checkOrder(t, got, []string{
			"include mk/flags.mk",
			".DEFAULT_GOAL :=",
			"include mk/repo.mk",
		})

		// Read ahead of the rest, so not again with them.
		if strings.Count(got, "include mk/flags.mk") != 1 {
			t.Errorf("want mk/flags.mk included exactly once:\n%s", got)
		}
	})

	t.Run("no flags fragment, no flags include", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "mk/repo.mk", "sprite:\n\t@echo sprite\n")

		got := generateAndRead(t, fs)

		if strings.Contains(got, "flags.mk") {
			t.Errorf("want no include for a fragment that is not there:\n%s", got)
		}

		if !strings.Contains(got, "include mk/repo.mk") {
			t.Errorf("want the fragment that is there included:\n%s", got)
		}
	})

	t.Run("every fragment is named", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		for _, name := range []string{"a.mk", "b.mk", "c.mk"} {
			writeFile(t, fs, "mk/"+name, "# nothing in particular\n")
		}

		got := generateAndRead(t, fs)

		checkOrder(t, got, []string{"include mk/a.mk", "include mk/b.mk", "include mk/c.mk"})
	})
}

// generateAndRead generates a Makefile and returns it, for the tests that
// only care about what came out.
func generateAndRead(t *testing.T, fs afero.Fs) string {
	t.Helper()

	if err := generateMakefile(fs, false); err != nil {
		t.Fatal(err)
	}

	return readFile(t, fs, makefilePath)
}

// TestGenerateMakefileBuildsUnderMake checks the build target against make
// and the Go toolchain: that a repository with one package under cmd/ gets
// a Makefile that really does produce the binary, and that mk/flags.mk
// reaches the recipe that needs it.
func TestGenerateMakefileBuildsUnderMake(t *testing.T) {
	for _, bin := range []string{"make", "go"} {
		if _, err := exec.LookPath(bin); err != nil {
			t.Skipf("%s is not installed", bin)
		}
	}

	dir := t.TempDir()
	fs := afero.NewBasePathFs(afero.NewOsFs(), dir)

	// A real filesystem, unlike the in-memory one, wants the directories
	// made first.
	for _, d := range []string{"cmd/worldweaver", makefileDir} {
		if err := fs.MkdirAll(d, 0o755); err != nil {
			t.Fatal(err)
		}
	}

	writeFile(t, fs, "go.mod", "module example.com/worldweaver\n\ngo 1.24\n")
	writeFile(t, fs, "cmd/worldweaver/main.go",
		"package main\n\nimport \"fmt\"\n\nfunc main() { fmt.Println(\"ran\") }\n")
	writeFile(t, fs, "mk/flags.mk", "SET_BY_FLAGS += yes\n")

	// A fragment of the repository's own, to ask what flags.mk left behind.
	// A target in a file rather than make's --eval, which Apple still ships
	// a make too old to have.
	writeFile(t, fs, "mk/probe.mk", "show:\n\t@echo [$(SET_BY_FLAGS)]\n")

	if err := generateMakefile(fs, false); err != nil {
		t.Fatal(err)
	}

	run := func(t *testing.T, args ...string) string {
		t.Helper()

		cmd := exec.CommandContext(t.Context(), "make", args...)
		cmd.Dir = dir

		out, err := cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("make %v: %v\n%s", args, err, out)
		}

		return string(out)
	}

	run(t, "build")

	if _, err := os.Stat(filepath.Join(dir, "bin", "worldweaver")); err != nil {
		t.Fatalf("make build did not produce the binary: %v", err)
	}

	// Read before the rest, and only once: included twice, the appended
	// value would be there twice over.
	if got := run(t, "-s", "show"); !strings.Contains(got, "[yes]") {
		t.Errorf("mk/flags.mk did not reach the recipe exactly once: %q", got)
	}
}

func TestHasBenchmarks(t *testing.T) {
	for _, tc := range []struct {
		name  string
		files map[string]string
		want  bool
	}{
		{"a benchmark", map[string]string{
			"x_test.go": "package x\n\nfunc BenchmarkX(b *testing.B) {}\n",
		}, true},
		{"tests but no benchmark", map[string]string{
			"x_test.go": "package x\n\nfunc TestX(t *testing.T) {}\n",
		}, false},
		{"nothing at all", nil, false},
		// A benchmark somebody vendored is not this repository's to run.
		{"only in vendor", map[string]string{
			"vendor/example.com/y/y_test.go": "package y\n\nfunc BenchmarkY(b *testing.B) {}\n",
		}, false},
		// The word in prose is not a declaration.
		{"only mentioned", map[string]string{
			"x_test.go": "package x\n\n// BenchmarkX would go here.\nfunc TestX(t *testing.T) {}\n",
		}, false},
		// Found first, with more of the tree left to walk: the case that
		// caught afero.Walk not knowing filepath.SkipAll.
		{"more files after the one with it", map[string]string{
			"a_test.go": "package x\n\nfunc BenchmarkA(b *testing.B) {}\n",
			"z_test.go": "package x\n\nfunc TestZ(t *testing.T) {}\n",
			"zz/z.go":   "package zz\n",
		}, true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			fs := afero.NewMemMapFs()
			for p, c := range tc.files {
				writeFile(t, fs, p, c)
			}

			got, err := hasBenchmarks(fs)
			if err != nil {
				t.Fatal(err)
			}

			if got != tc.want {
				t.Errorf("hasBenchmarks = %v, want %v", got, tc.want)
			}
		})
	}
}

// TestGenerateMakefileBench checks that bench is written only where there
// is something to benchmark.
func TestGenerateMakefileBench(t *testing.T) {
	for _, tc := range []struct {
		name string
		test string
		want bool
	}{
		{"with benchmarks", "package x\n\nfunc BenchmarkX(b *testing.B) {}\n", true},
		{"without", "package x\n\nfunc TestX(t *testing.T) {}\n", false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			fs := afero.NewMemMapFs()
			writeFile(t, fs, "x_test.go", tc.test)

			got := generateAndRead(t, fs)

			if strings.Contains(got, "bench:") != tc.want {
				t.Errorf("bench target present = %v, want %v:\n%s", !tc.want, tc.want, got)
			}
		})
	}
}

// TestGenerateMakefileDollarEscaping guards the one recipe that needs a
// dollar sign to reach the shell rather than make.
func TestGenerateMakefileDollarEscaping(t *testing.T) {
	fs := afero.NewMemMapFs()
	writeFile(t, fs, "x_test.go", "package x\n\nfunc BenchmarkX(b *testing.B) {}\n")

	got := generateAndRead(t, fs)

	// "-run=^$" alone would have make eat the dollar, leaving "-run=^",
	// which matches every test rather than none of them.
	if !strings.Contains(got, "go test -run=^$$ -bench=.") {
		t.Errorf("want the dollar doubled for make:\n%s", got)
	}
}

// TestGenerateMakefileTools covers what took two goes to get right: a tool
// that analyses this module has to be built with a Go at least as new as
// the module targets, and "go install" alone honours the tool's own pinned
// toolchain, which can be older. Both golangci-lint and govulncheck then
// refuse to run at all.
func TestGenerateMakefileTools(t *testing.T) {
	got := generateAndRead(t, afero.NewMemMapFs())

	checkOrder(t, got, []string{
		"TOOL_GO := $(shell go env GOVERSION)",
		"tools:",
		"GOTOOLCHAIN=$(TOOL_GO) go install github.com/golangci/golangci-lint",
		"GOTOOLCHAIN=$(TOOL_GO) go install golang.org/x/vuln/cmd/govulncheck",
	})

	// Nothing to install, nothing to say about which Go to install it with.
	fs := afero.NewMemMapFs()
	writeFile(t, fs, "mk/repo.mk", "tools:\n\t@echo mine\n")

	if own := generateAndRead(t, fs); strings.Contains(own, "TOOL_GO") {
		t.Errorf("want no TOOL_GO where the repository installs its own tools:\n%s", own)
	}
}

// TestGenerateMakefileBundles checks the bundles: the race detector rather
// than plain test, fix ahead of verify so what it changes shows up as
// drift, and no lint alongside fix, which lints as it goes.
func TestGenerateMakefileBundles(t *testing.T) {
	got := generateAndRead(t, afero.NewMemMapFs())

	// One a superset of the other: ci is what runs anywhere, all adds what
	// needs the network.
	checkOrder(t, got, []string{
		"all: ci vuln",
		"ci: fix verify vet test-race",
	})

	for _, want := range []string{
		"vet:\n\tgo vet ./...",
		"vuln:\n\tgovulncheck ./...",
		// tidy needs to resolve the module graph, which a sandbox without
		// credentials for a private dependency cannot do, so it is not in
		// the bundle an agent is told to run.
		"verify: generate\n\tgit diff --exit-code",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q:\n%s", want, got)
		}
	}

	for _, want := range []string{
		"test:\n\tgo test ./...",
		"test-race:\n\tgo test -race ./...",
		// Composites reuse the target rather than repeating its recipe.
		"deps:\n\tgo get -u ./...\n\t$(MAKE) tidy",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q:\n%s", want, got)
		}
	}

	// Prerequisite order is what sequences a bundle, so -j must not
	// reorder it.
	if !strings.Contains(got, ".NOTPARALLEL:") {
		t.Errorf("want .NOTPARALLEL, since bundles rely on prerequisite order:\n%s", got)
	}
}

// TestGenerateMakefileCleanIsExtensible checks the hook a repository uses
// to have clean remove its own artefacts: CLEAN_FILES is a variable read
// when the recipe runs, so a fragment included below can still add to it.
func TestGenerateMakefileCleanIsExtensible(t *testing.T) {
	fs := afero.NewMemMapFs()
	writeFile(t, fs, "cmd/tool/main.go", "package main\n")

	got := generateAndRead(t, fs)

	checkOrder(t, got, []string{
		"CLEAN_FILES := bin cover.out",
		"clean:", "rm -rf $(CLEAN_FILES)",
	})
}

// TestGenerateMakefileToolPathUnderMake checks the PATH export against make
// itself: that a recipe finds the tool where "go install" put it even when
// an older copy sits earlier on the caller's PATH. That shadowing is the
// failure the export exists to prevent, and it is not something a text
// assertion can tell you anything about.
func TestGenerateMakefileToolPathUnderMake(t *testing.T) {
	if _, err := exec.LookPath("make"); err != nil {
		t.Skip("make is not installed")
	}

	dir := t.TempDir()
	fs := afero.NewBasePathFs(afero.NewOsFs(), dir)

	for _, d := range []string{makefileDir, "shadow", "toolbin"} {
		if err := fs.MkdirAll(d, 0o755); err != nil {
			t.Fatal(err)
		}
	}

	// Two copies of the same command: one where GOBIN puts it, one earlier
	// on the PATH make is called with.
	for _, where := range []string{"shadow", "toolbin"} {
		script := filepath.Join(dir, where, "housetool")
		if err := os.WriteFile(script, []byte("#!/bin/sh\necho from-"+where+"\n"), 0o755); err != nil {
			t.Fatal(err)
		}
	}

	// A fragment of the repository's own, since no house target shells out
	// to something a test can install.
	writeFile(t, fs, "mk/probe.mk", "which:\n\t@housetool\n")

	if err := generateMakefile(fs, false); err != nil {
		t.Fatal(err)
	}

	cmd := exec.CommandContext(t.Context(), "make", "-s", "which")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(),
		"GOBIN="+filepath.Join(dir, "toolbin"),
		"PATH="+filepath.Join(dir, "shadow")+string(os.PathListSeparator)+os.Getenv("PATH"),
	)

	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("make which: %v\n%s", err, out)
	}

	if got := strings.TrimSpace(string(out)); got != "from-toolbin" {
		t.Errorf("recipe ran %q, want the copy in GOBIN: the PATH export is not working", got)
	}
}
