package maintain

import (
	"strings"
	"testing"

	"github.com/spf13/afero"
)

// oldStamp is what every generated file in every repository still carries:
// this package used to be portfolio's. The marker has to go on recognising
// it, because the alternative is that one run reads thirty repositories'
// generated files as hand-written and adopts them.
const oldStamp = "generated by MarkRosemaker/portfolio"

func TestGeneratedMarkerMatchesAnyGenerator(t *testing.T) {
	for _, tc := range []struct {
		name string
		line string
		want bool
	}{
		{"this generator", "<!-- " + generatedBy + " — edit files in README/ instead. -->", true},
		{"the one before it", "<!-- " + oldStamp + " — edit files in README/ instead. -->", true},
		{"one nobody has written yet", "<!-- generated by example.com/other — edit files in mk/ instead. -->", true},
		{"a hash comment", "# " + oldStamp + " — edit files in mk/ instead.", true},
		{"prose that says the words", "This file was generated by hand, more or less.", false},
		{"a hand-written Makefile", "# a Makefile somebody wrote", false},
		{"empty", "", false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if got := generatedMarker.MatchString(tc.line); got != tc.want {
				t.Errorf("match = %v, want %v, for %q", got, tc.want, tc.line)
			}
		})
	}
}

// TestReadmeStampedByTheOldGeneratorIsNotAdopted is the failure the regex
// exists to prevent: adoption splits a README into README/ fragments, so a
// generated one mistaken for hand-written would be folded into
// README/description.md and then regenerated around itself, leaving two
// stamps and the whole file duplicated.
func TestReadmeStampedByTheOldGeneratorIsNotAdopted(t *testing.T) {
	fs := afero.NewMemMapFs()
	writeFile(t, fs, readmePath,
		"<!-- "+oldStamp+" — edit files in README/ instead. -->\nA blurb.\n")

	if err := generateReadme(fs, "user", "gorepo", true, 80); err != nil {
		t.Fatal(err)
	}

	got := readFile(t, fs, readmePath)

	if n := strings.Count(got, "generated by"); n != 1 {
		t.Errorf("%d stamps, want 1 — the old one was adopted:\n%s", n, got)
	}

	if !strings.Contains(got, generatedBy) {
		t.Errorf("the rewrite did not carry this generator's stamp:\n%s", got)
	}
}

// TestGitignoreBlockStampedByTheOldGeneratorIsRewritten: the block is found
// by its marker, so an unrecognised one would leave the old block orphaned
// and a second one written above it.
func TestGitignoreBlockStampedByTheOldGeneratorIsRewritten(t *testing.T) {
	fs := afero.NewMemMapFs()
	writeFile(t, fs, gitignorePath,
		"# "+oldStamp+" — this block only; your own rules go below it.\n"+
			"something-stale\n"+
			"# end "+oldStamp+"\n"+
			"mine\n")

	got := generateGitignoreAndRead(t, fs)

	if n := strings.Count(got, "this block only"); n != 1 {
		t.Errorf("%d opening markers, want 1:\n%s", n, got)
	}

	if strings.Contains(got, "something-stale") {
		t.Errorf("the old block was not rewritten:\n%s", got)
	}

	if strings.Contains(got, oldStamp) {
		t.Errorf("the block still carries the old stamp:\n%s", got)
	}

	if !strings.HasSuffix(got, "mine\n") {
		t.Errorf("the repository's own rules did not survive:\n%s", got)
	}
}

// TestMakefileStampedByTheOldGeneratorIsNotAdopted: adoption moves the file
// to mk/legacy.mk and includes it, so a generated Makefile mistaken for a
// hand-written one leaves the repository with its own Makefile twice — once
// as a fragment and once as the file that includes it.
//
// This one happened. The Makefile's adoption check matched the stamp this
// run writes rather than the marker, so renaming the generator adopted
// devtool's own Makefile on the first run after the rename.
func TestMakefileStampedByTheOldGeneratorIsNotAdopted(t *testing.T) {
	fs := afero.NewMemMapFs()
	writeFile(t, fs, makefilePath,
		"# "+oldStamp+" — edit files in mk/ instead.\n.DEFAULT_GOAL := all\n\nall:\n\techo hi\n")

	if err := generateMakefile(fs, true); err != nil {
		t.Fatal(err)
	}

	adopted, err := afero.Exists(fs, "mk/legacy.mk")
	if err != nil {
		t.Fatal(err)
	}

	if adopted {
		t.Errorf("a generated Makefile was adopted as a legacy fragment:\n%s",
			readFile(t, fs, "mk/legacy.mk"))
	}

	if got := readFile(t, fs, makefilePath); !strings.HasPrefix(got, "# "+generatedBy) {
		t.Errorf("the rewrite did not carry this generator's stamp:\n%s", got)
	}
}
