package maintain

import (
	"bytes"
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/MarkRosemaker/openapi"
	"github.com/spf13/afero"
)

// update rewrites the golden files instead of comparing against them.
var update = flag.Bool("update", false, "rewrite the testdata golden files")

// wantStamp is the generated-file marker spelled out, rather than read from
// the template the code under test renders: a test that took it from there
// could not notice it changing.
const wantStamp = "<!-- generated by MarkRosemaker/portfolio — edit files in README/ instead. -->"

func TestGenerateReadme(t *testing.T) {
	t.Run("nothing written yet gets a minimal, valid README", func(t *testing.T) {
		fs := afero.NewMemMapFs()

		if err := generateReadme(fs, "user", "gorepo", false, 96.4); err != nil {
			t.Fatal(err)
		}

		got := readFile(t, fs, readmePath)

		if !strings.Contains(got, wantStamp) {
			t.Errorf("missing stamp: %s", got)
		}

		if !strings.Contains(got, "github.com/user/gorepo") {
			t.Errorf("missing the repository in a badge link: %s", got)
		}

		if !strings.Contains(got, "## Additional Information") {
			t.Errorf("missing the generated footer: %s", got)
		}
	})

	// Nothing else here, so nothing survives the private gate. A private
	// repository that has the conventional documents does get the footer's
	// first section — see TestGenerateReadmeLinksConventionalDocs.
	t.Run("a private repository with nothing else gets no public badges or footer", func(t *testing.T) {
		fs := afero.NewMemMapFs()

		if err := generateReadme(fs, "user", "gorepo", true, 96.4); err != nil {
			t.Fatal(err)
		}

		got := readFile(t, fs, readmePath)

		for _, want := range []string{"pkg.go.dev", "license-Apache", "## Additional Information", "## License"} {
			if strings.Contains(got, want) {
				t.Errorf("a private repository should not get %q: %s", want, got)
			}
		}

		// One badge it does keep: coverage is for whoever owns the
		// repository, not for an audience.
		if !strings.Contains(got, "badge/coverage-96%25-brightgreen") {
			t.Errorf("a private repository should still get its coverage badge: %s", got)
		}
	})

	t.Run("fragments are embedded under their own headings", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "README/description.md", "A longer blurb about the thing.\n")
		writeFile(t, fs, "README/intro.md", "Some background.\n")
		writeFile(t, fs, "README/features.md", "- fast\n- correct\n")
		writeFile(t, fs, "README/usage.md", "`gorepo run`\n")
		writeFile(t, fs, "README/examples.md", "See examples/.\n")
		writeFile(t, fs, "README/tail.md", "Thanks for reading.\n")

		if err := generateReadme(fs, "user", "gorepo", false, 96.4); err != nil {
			t.Fatal(err)
		}

		checkOrder(t, readFile(t, fs, readmePath), []string{
			wantStamp,
			"A longer blurb about the thing.",
			"## Introduction", "Some background.",
			"## Features", "fast",
			"## Usage", "gorepo run",
			"## Examples", "See examples/.",
			"Thanks for reading.",
			"## Additional Information",
		})
	})

	t.Run("frontmatter carries the tagline and logo, and never reaches the output as prose", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "docs/logo.png", "PNG")
		writeFile(t, fs, "README/description.md",
			"---\ntagline: Does a thing, well.\nlogo:\n  alt: gorepo logo\n  source: docs/logo.png\n  width: 240\n---\n\nA longer blurb.\n")

		if err := generateReadme(fs, "user", "gorepo", false, 96.4); err != nil {
			t.Fatal(err)
		}

		got := readFile(t, fs, readmePath)

		for _, want := range []string{
			`<h3 align="center">Does a thing, well.</h3>`,
			`alt="gorepo logo"`, `src="docs/logo.png"`, `width="240"`,
			"A longer blurb.",
		} {
			if !strings.Contains(got, want) {
				t.Errorf("missing %q: %s", want, got)
			}
		}

		if strings.Contains(got, "tagline:") || strings.Contains(got, "---") {
			t.Errorf("frontmatter leaked into the output as prose: %s", got)
		}
	})

	t.Run("logo width defaults to 500 when left out", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "docs/logo.png", "PNG")
		writeFile(t, fs, "README/description.md",
			"---\nlogo:\n  alt: gorepo logo\n  source: docs/logo.png\n---\n\nA blurb.\n")

		if err := generateReadme(fs, "user", "gorepo", false, 96.4); err != nil {
			t.Fatal(err)
		}

		if got := readFile(t, fs, readmePath); !strings.Contains(got, `width="500"`) {
			t.Errorf(`missing width="500": %s`, got)
		}
	})

	t.Run("a fragment whose body only looks like frontmatter is left as prose", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		// No closing delimiter, so this is a horizontal rule, not frontmatter.
		writeFile(t, fs, "README/description.md", "---\nnot frontmatter at all\n")

		if err := generateReadme(fs, "user", "gorepo", false, 96.4); err != nil {
			t.Fatal(err)
		}

		if got := readFile(t, fs, readmePath); !strings.Contains(got, "not frontmatter at all") {
			t.Errorf("body was swallowed as frontmatter: %s", got)
		}
	})

	t.Run("invalid frontmatter YAML is rejected", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "README/description.md", "---\nnot: [valid: yaml\n---\n\nA blurb.\n")

		if err := generateReadme(fs, "user", "gorepo", false, 96.4); err == nil {
			t.Fatal("expected an error for invalid frontmatter, got nil")
		}
	})

	t.Run("a hidden fragment is never read", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "README/.description.md", "should not appear")

		if err := generateReadme(fs, "user", "gorepo", false, 96.4); err != nil {
			t.Fatal(err)
		}

		if got := readFile(t, fs, readmePath); strings.Contains(got, "should not appear") {
			t.Errorf("a hidden fragment should never be read: %s", got)
		}
	})

	// A file sitting in README/ looks like it is being rendered. Skipping it
	// quietly would leave whoever wrote it wondering where their words went,
	// so it is an error — and one that says what the recognised names are.
	t.Run("an unrecognised entry is an error, not something skipped", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "README/custom.md", "where did this go?")

		err := generateReadme(fs, "user", "gorepo", false, 96.4)
		if err == nil {
			t.Fatal("expected an error for an unrecognised fragment, got nil")
		}

		for _, want := range []string{"README/custom.md", "description.md"} {
			if !strings.Contains(err.Error(), want) {
				t.Errorf("error does not mention %q: %v", want, err)
			}
		}
	})

	t.Run("a directory in README/ is an error too", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		if err := fs.MkdirAll("README/description.md", 0o755); err != nil {
			t.Fatal(err)
		}

		if err := generateReadme(fs, "user", "gorepo", false, 96.4); err == nil {
			t.Fatal("expected an error for a directory where a fragment belongs, got nil")
		}
	})

	t.Run("non-UTF-8 fragment content is rejected", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		if err := afero.WriteFile(fs, "README/description.md", []byte{0xff, 0xfe, 0x00}, 0o644); err != nil {
			t.Fatal(err)
		}

		if err := generateReadme(fs, "user", "gorepo", false, 96.4); err == nil {
			t.Fatal("expected an error for non-UTF-8 fragment content, got nil")
		}
	})

	t.Run("output never has more than one blank line in a row", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "README/description.md", "---\ntagline: A tagline.\n---\n\nA blurb.\n")

		if err := generateReadme(fs, "user", "gorepo", false, 96.4); err != nil {
			t.Fatal(err)
		}

		if got := readFile(t, fs, readmePath); strings.Contains(got, "\n\n\n") {
			t.Errorf("output has more than one blank line in a row:\n%s", got)
		}
	})

	t.Run("running twice produces byte-identical output", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "README/description.md", "A blurb.\n")
		writeFile(t, fs, "README/usage.md", "`gorepo run`\n")

		if err := generateReadme(fs, "user", "gorepo", false, 96.4); err != nil {
			t.Fatal(err)
		}

		first := readFile(t, fs, readmePath)

		if err := generateReadme(fs, "user", "gorepo", false, 96.4); err != nil {
			t.Fatal(err)
		}

		if second := readFile(t, fs, readmePath); first != second {
			t.Errorf("output changed between runs:\nfirst:  %q\nsecond: %q", first, second)
		}
	})
}

// TestGenerateReadmeAdoptsExisting covers taking over a README.md written
// before this task existed: the interesting case, since it is the only one
// that can lose someone's work.
func TestGenerateReadmeAdoptsExisting(t *testing.T) {
	const handWritten = `# gorepo

[![Go Reference](https://pkg.go.dev/badge/github.com/user/gorepo.svg)](https://pkg.go.dev/github.com/user/gorepo)

<p align="center">
  <img alt="gorepo logo" src=docs/logo.png width=240>
</p>

<h3 align="center">
  Does a thing, well.
</h3>

A longer blurb about the thing.

## Features

- fast
- correct

## Usage

` + "`gorepo run`" + `

## Prior art

Somebody else's thing.

## License

Apache 2.0, see LICENSE.
`

	t.Run("an existing README is split into fragments and rendered back", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, readmePath, handWritten)
		writeFile(t, fs, "docs/logo.png", "PNG")

		if err := generateReadme(fs, "user", "gorepo", false, 96.4); err != nil {
			t.Fatal(err)
		}

		// The prose is split out by heading...
		for name, want := range map[string]string{
			"README/description.md": "A longer blurb about the thing.",
			"README/features.md":    "- fast",
			"README/usage.md":       "`gorepo run`",
			"README/tail.md":        "## Prior art",
		} {
			if got := readFile(t, fs, name); !strings.Contains(got, want) {
				t.Errorf("%s = %q, want it to contain %q", name, got, want)
			}
		}

		// ...the logo and tagline become frontmatter, not prose...
		desc := readFile(t, fs, "README/description.md")
		for _, want := range []string{"tagline: Does a thing, well.", "alt: gorepo logo", "source: docs/logo.png", "width: 240"} {
			if !strings.Contains(desc, want) {
				t.Errorf("description.md is missing frontmatter %q:\n%s", want, desc)
			}
		}

		// ...and no fragment keeps what the template writes for itself.
		for name, unwanted := range map[string]string{
			"README/description.md": "pkg.go.dev",
			"README/tail.md":        "## License",
		} {
			if got := readFile(t, fs, name); strings.Contains(got, unwanted) {
				t.Errorf("%s kept %q, which the template writes itself:\n%s", name, unwanted, got)
			}
		}

		// The same run renders README.md rather than waiting for the next.
		got := readFile(t, fs, readmePath)
		if !strings.Contains(got, wantStamp) {
			t.Errorf("README.md was not rendered in the same run:\n%s", got)
		}

		if strings.Contains(got, "README/legacy.md") {
			t.Error("a split README should not also produce a legacy dump")
		}

		if exists, err := afero.Exists(fs, "README/legacy.md"); err != nil {
			t.Fatal(err)
		} else if exists {
			t.Error("legacy.md should not exist once the README was split")
		}
	})

	t.Run("nothing is lost: every heading ends up somewhere", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, readmePath, handWritten)
		writeFile(t, fs, "docs/logo.png", "PNG")

		if err := generateReadme(fs, "user", "gorepo", false, 96.4); err != nil {
			t.Fatal(err)
		}

		got := readFile(t, fs, readmePath)

		checkOrder(t, got, []string{
			`<img alt="gorepo logo"`,
			`<h3 align="center">Does a thing, well.</h3>`,
			"A longer blurb about the thing.",
			"## Features", "- fast",
			"## Usage", "`gorepo run`",
			"## Prior art", "Somebody else's thing.",
			"## Additional Information",
		})
	})

	t.Run("a README with nothing recognisable is kept whole in legacy.md", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		// A title and badges are all things the template writes itself, so
		// there is nothing here worth a fragment.
		const thin = "# gorepo\n\n[![Go Reference](https://pkg.go.dev/badge/x.svg)](https://pkg.go.dev/x)\n"
		writeFile(t, fs, readmePath, thin)

		if err := generateReadme(fs, "user", "gorepo", false, 96.4); err != nil {
			t.Fatal(err)
		}

		if got := readFile(t, fs, "README/legacy.md"); got != thin {
			t.Errorf("legacy.md = %q, want the original README content", got)
		}

		if got := readFile(t, fs, readmePath); got != thin {
			t.Errorf("README.md was touched, want it left exactly as it was: %s", got)
		}
	})

	t.Run("a legacy fragment already present freezes README.md entirely", func(t *testing.T) {
		fs := afero.NewMemMapFs()

		const content = "# gorepo\n\nSome hand-written prose.\n"
		writeFile(t, fs, readmePath, content)
		writeFile(t, fs, "README/legacy.md", content)
		// A real fragment must not take over while legacy.md has not been
		// dealt with by a human yet.
		writeFile(t, fs, "README/description.md", "should not be used")

		err := generateReadme(fs, "user", "gorepo", false, 96.4)
		if disallowLegacy {
			if err == nil {
				t.Fatal("expected error")
			}
			return
		} else if err != nil {
			t.Fatal(err)
		}

		if got := readFile(t, fs, readmePath); got != content {
			t.Errorf("README.md changed while a legacy fragment was present: %s", got)
		}
	})

	t.Run("adopting is idempotent: a second run changes nothing", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, readmePath, handWritten)
		writeFile(t, fs, "docs/logo.png", "PNG")

		if err := generateReadme(fs, "user", "gorepo", false, 96.4); err != nil {
			t.Fatal(err)
		}

		first, firstDesc := readFile(t, fs, readmePath), readFile(t, fs, "README/description.md")

		if err := generateReadme(fs, "user", "gorepo", false, 96.4); err != nil {
			t.Fatal(err)
		}

		if second := readFile(t, fs, readmePath); first != second {
			t.Errorf("README.md changed on the second run:\nfirst:  %q\nsecond: %q", first, second)
		}

		if second := readFile(t, fs, "README/description.md"); firstDesc != second {
			t.Errorf("description.md changed on the second run:\nfirst:  %q\nsecond: %q", firstDesc, second)
		}
	})
}

func TestSplitFrontmatter(t *testing.T) {
	for _, tc := range []struct {
		name                string
		in                  string
		wantFront, wantBody string
	}{
		{"none", "just a body\n", "", "just a body\n"},
		{"closed block", "---\ntagline: x\n---\n\nbody\n", "tagline: x\n", "\nbody\n"},
		{"no trailing newline after the close", "---\ntagline: x\n---", "tagline: x\n", ""},
		// An unclosed "---" is a horizontal rule, not frontmatter.
		{"unclosed", "---\nnot frontmatter\n", "", "---\nnot frontmatter\n"},
		{"delimiter not at the start", "intro\n---\ntagline: x\n---\n", "", "intro\n---\ntagline: x\n---\n"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			front, body := splitFrontmatter([]byte(tc.in))

			if string(front) != tc.wantFront {
				t.Errorf("front = %q, want %q", front, tc.wantFront)
			}

			if string(body) != tc.wantBody {
				t.Errorf("body = %q, want %q", body, tc.wantBody)
			}
		})
	}
}

// checkOrder fails the test if want does not appear, in order, within got —
// each entry may be preceded by other text, but never by a later one.
func checkOrder(t *testing.T, got string, want []string) {
	t.Helper()

	pos := 0

	for _, w := range want {
		i := strings.Index(got[pos:], w)
		if i < 0 {
			t.Fatalf("expected %q to appear after position %d in: %s", w, pos, got)
		}

		pos += i + len(w)
	}
}

func writeFile(t *testing.T, fs afero.Fs, path, content string) {
	t.Helper()

	if err := afero.WriteFile(fs, path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func readFile(t *testing.T, fs afero.Fs, path string) string {
	t.Helper()

	b, err := afero.ReadFile(fs, path)
	if err != nil {
		t.Fatal(err)
	}

	return string(b)
}

// TestSplitLegacyReadmeCodeFence checks that a "## " line inside a fenced
// code block is code, not a heading: splitting there would cut the block in
// half and break the Markdown.
func TestSplitLegacyReadmeCodeFence(t *testing.T) {
	fragments, err := splitLegacyReadme([]byte("A blurb.\n\n## Usage\n\n```sh\n## not a heading\ngorepo run\n```\n"), nil)
	if err != nil {
		t.Fatal(err)
	}

	usage := string(fragments["usage.md"])

	for _, want := range []string{"```sh", "## not a heading", "gorepo run", "```"} {
		if !strings.Contains(usage, want) {
			t.Errorf("usage.md lost %q:\n%s", want, usage)
		}
	}

	if got := string(fragments["tail.md"]); got != "" {
		t.Errorf("a fenced line was treated as an unrecognised heading: %q", got)
	}
}

// TestInferLogo covers guessing a logo from the repository root, which only
// happens when there is nothing to get wrong: one image, and only one.
func TestInferLogo(t *testing.T) {
	for _, tc := range []struct {
		name       string
		files      []string
		wantSource string
	}{
		{"one image", []string{"logo.png", "main.go", "go.mod"}, "logo.png"},
		{"one image, uppercase extension", []string{"Logo.SVG"}, "Logo.SVG"},
		// Which of the two is the logo is anybody's guess, so neither is.
		{"two images", []string{"logo.png", "screenshot.png"}, ""},
		{"no images", []string{"main.go", "go.mod"}, ""},
		// A hidden file is not part of what a README shows.
		{"hidden image", []string{".logo.png"}, ""},
	} {
		t.Run(tc.name, func(t *testing.T) {
			fs := afero.NewMemMapFs()
			for _, f := range tc.files {
				writeFile(t, fs, f, "x")
			}

			logo, err := inferLogo(fs, "gorepo")
			if err != nil {
				t.Fatal(err)
			}

			if tc.wantSource == "" {
				if logo != nil {
					t.Fatalf("inferLogo = %+v, want nil", logo)
				}

				return
			}

			if logo == nil {
				t.Fatalf("inferLogo = nil, want source %q", tc.wantSource)
			}

			if logo.Source != tc.wantSource {
				t.Errorf("source = %q, want %q", logo.Source, tc.wantSource)
			}

			if want := "gorepo logo"; logo.Alt != want {
				t.Errorf("alt = %q, want %q", logo.Alt, want)
			}
		})
	}
}

// TestGenerateReadmeInfersLogoOnAdoption checks that a README showing its
// logo in a way the split cannot recognise still ends up with one, written
// into frontmatter where a human can correct the guess.
func TestGenerateReadmeInfersLogoOnAdoption(t *testing.T) {
	fs := afero.NewMemMapFs()
	writeFile(t, fs, readmePath, "# gorepo\n\nA blurb.\n\n<img src=\"logo.png\">\n")
	writeFile(t, fs, "logo.png", "PNG")

	if err := generateReadme(fs, "user", "gorepo", false, 96.4); err != nil {
		t.Fatal(err)
	}

	desc := readFile(t, fs, "README/description.md")

	for _, want := range []string{"logo:", "source: logo.png", "alt: gorepo logo"} {
		if !strings.Contains(desc, want) {
			t.Errorf("description.md is missing %q:\n%s", want, desc)
		}
	}

	if got := readFile(t, fs, readmePath); !strings.Contains(got, `src="logo.png"`) {
		t.Errorf("the inferred logo did not reach the README:\n%s", got)
	}
}

func TestValidateLogo(t *testing.T) {
	fs := afero.NewMemMapFs()
	writeFile(t, fs, "docs/logo.png", "PNG")

	if err := fs.MkdirAll("assets", 0o755); err != nil {
		t.Fatal(err)
	}

	for _, tc := range []struct {
		name    string
		logo    readmeLogo
		wantErr bool
	}{
		{"a file in the repository", readmeLogo{Source: "docs/logo.png"}, false},
		{"a remote URL is taken on trust", readmeLogo{Source: "https://example.com/logo.png"}, false},
		{"a protocol-relative URL too", readmeLogo{Source: "//example.com/logo.png"}, false},
		{"a file that is not there", readmeLogo{Source: "docs/missing.png"}, true},
		{"a directory", readmeLogo{Source: "assets"}, true},
		{"no source at all", readmeLogo{Alt: "gorepo logo"}, true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			err := validateLogo(fs, &tc.logo)

			if tc.wantErr && err == nil {
				t.Fatalf("validateLogo(%+v) = nil, want an error", tc.logo)
			}

			if !tc.wantErr && err != nil {
				t.Fatalf("validateLogo(%+v) = %v, want nil", tc.logo, err)
			}
		})
	}
}

// TestGenerateReadmeRejectsBrokenLogo checks that the validation is wired
// into the task, not just available to it: a README with a broken image at
// the top of it is not worth publishing.
func TestGenerateReadmeRejectsBrokenLogo(t *testing.T) {
	fs := afero.NewMemMapFs()
	writeFile(t, fs, "README/description.md",
		"---\nlogo:\n  source: docs/missing.png\n---\n\nA blurb.\n")

	err := generateReadme(fs, "user", "gorepo", false, 96.4)
	if err == nil {
		t.Fatal("expected an error for a logo source that is not in the repository, got nil")
	}

	if !strings.Contains(err.Error(), "docs/missing.png") {
		t.Errorf("error does not name the offending source: %v", err)
	}
}

// readmeCases are the field combinations the golden files and the
// whitespace check both run over: everything at once, nothing at all, and
// the cases in between where a section's absence could leave a hole.
var readmeCases = []struct {
	name string
	data readmeData
}{
	{"full", readmeData{
		Owner: "user", Name: "gorepo", Coverage: 96,
		Logo:        &readmeLogo{Alt: "gorepo logo", Source: "logo.png", Width: 240},
		Tagline:     "Does a thing, well.",
		Description: "A longer blurb about the thing.",
		Intro:       "Some background.",
		Features:    "- fast\n- correct",
		Usage:       "`gorepo run`",
		Examples:    "See examples/.",
		Tail:        "Thanks for reading.",
		Docs:        conventionalDocs,
	}},
	{"minimal", readmeData{Owner: "user", Name: "gorepo", Coverage: 100}},
	{"private", readmeData{Owner: "user", Name: "gorepo", Private: true, Coverage: 42, Description: "A blurb."}},
	// A private repository still gets the footer's first section, and only
	// that one: the documents are beside the README, Contributing is not.
	{"private-docs", readmeData{
		Owner: "user", Name: "gorepo", Private: true, Coverage: 42,
		Description: "A blurb.",
		Docs:        conventionalDocs,
	}},
	// Only one of the two, which is the shape of a repository that has an
	// architecture note and nothing planned.
	{"one-doc", readmeData{
		Owner: "user", Name: "gorepo", Coverage: 70,
		Description: "A blurb.",
		Docs:        conventionalDocs[:1],
	}},
	{"description-only", readmeData{Owner: "user", Name: "gorepo", Coverage: 0, Description: "A blurb."}},
	{"logo-default-width", readmeData{
		Owner: "user", Name: "gorepo", Coverage: 61,
		Logo: &readmeLogo{Alt: "gorepo logo", Source: "logo.png"},
	}},
	{"openapi", readmeData{
		Owner: "user", Name: "gorepo", Coverage: 88,
		OpenAPI:     &openapi.Document{OpenAPI: "3.1.0"},
		Description: "A blurb.",
	}},
}

// TestReadmeTemplateWhitespace holds the template to generating the blank
// lines itself, correctly, rather than being tidied up afterwards: whatever
// combination of sections renders, no run of blank lines and no leading one.
func TestReadmeTemplateWhitespace(t *testing.T) {
	for _, tc := range readmeCases {
		t.Run(tc.name, func(t *testing.T) {
			buf := &bytes.Buffer{}
			if err := readmeTmpl.Execute(buf, tc.data); err != nil {
				t.Fatal(err)
			}

			raw := buf.String()

			if strings.Contains(raw, "\n\n\n") {
				t.Errorf("raw template output has more than one blank line in a row:\n%q", raw)
			}

			if strings.HasPrefix(raw, "\n") {
				t.Errorf("raw template output starts with a blank line: %q", raw)
			}

			// The stamp is an HTML comment: invisible once rendered, so
			// whatever follows it needs no blank line of its own.
			if strings.Contains(raw, wantStamp+"\n\n") {
				t.Errorf("a blank line follows the stamp: %q", raw)
			}
		})
	}
}

// TestReadmeGolden renders each case against a golden file, so a change to
// the template shows up as a reviewable diff rather than as prose in a test
// assertion. Run "go test ./maintain -update" to rewrite them.
func TestReadmeGolden(t *testing.T) {
	for _, tc := range readmeCases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := renderReadme(tc.data)
			if err != nil {
				t.Fatal(err)
			}

			golden := filepath.Join("testdata", "README."+tc.name+".golden")

			if *update {
				if err := os.WriteFile(golden, got, 0o644); err != nil {
					t.Fatal(err)
				}

				return
			}

			want, err := os.ReadFile(golden)
			if err != nil {
				t.Fatalf("%v (run: go test ./maintain -update)", err)
			}

			if !bytes.Equal(got, want) {
				t.Errorf("%s does not match:\n--- got ---\n%s\n--- want ---\n%s", golden, got, want)
			}
		})
	}
}

func TestCoverageColor(t *testing.T) {
	for _, tc := range []struct {
		coverage int
		want     string
	}{
		{100, "brightgreen"},
		{90, "brightgreen"},
		{89, "green"},
		{75, "green"},
		{74, "yellowgreen"},
		{60, "yellowgreen"},
		{59, "yellow"},
		{45, "yellow"},
		{44, "orange"},
		{30, "orange"},
		{29, "red"},
		{0, "red"},
	} {
		if got := (readmeData{Coverage: tc.coverage}).CoverageColor(); got != tc.want {
			t.Errorf("coverage %d: colour = %q, want %q", tc.coverage, got, tc.want)
		}
	}
}

// TestCoverageIsWholePercent checks the figure is cast rather than rounded,
// so a badge never claims a percent the run did not measure.
func TestCoverageIsWholePercent(t *testing.T) {
	fs := afero.NewMemMapFs()

	if err := generateReadme(fs, "user", "gorepo", false, 96.8); err != nil {
		t.Fatal(err)
	}

	if got := readFile(t, fs, readmePath); !strings.Contains(got, "coverage-96%25-") {
		t.Errorf("want coverage 96 from 96.8: %s", got)
	}
}

// validOpenAPI is the smallest document that passes Validate: a
// specification version, an info block with a title and a version, and at
// least one of paths, webhooks or components.
const validOpenAPI = `{
  "openapi": "3.1.0",
  "info": {"title": "Gorepo API", "version": "1.4.2"},
  "paths": {
    "/things": {
      "get": {
        "responses": {"200": {"description": "every thing"}}
      }
    }
  }
}`

func TestGenerateReadmeOpenAPI(t *testing.T) {
	t.Run("a repository describing an API gets a badge for it", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, openAPIPath, validOpenAPI)
		writeFile(t, fs, "README/description.md", "A blurb.\n")

		if err := generateReadme(fs, "user", "gorepo", false, 96.4); err != nil {
			t.Fatal(err)
		}

		got := readFile(t, fs, readmePath)

		// The badge carries the specification version the document conforms
		// to, not the API's own version — which is deliberately different
		// in the fixture so the two cannot be confused.
		if !strings.Contains(got, "badge/OpenAPI-3.1.0-blue") {
			t.Errorf("missing the OpenAPI badge: %s", got)
		}

		if strings.Contains(got, "1.4.2") {
			t.Errorf("the badge shows the API's own version, not the spec's: %s", got)
		}
	})

	t.Run("a repository without one gets no badge", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "README/description.md", "A blurb.\n")

		if err := generateReadme(fs, "user", "gorepo", false, 96.4); err != nil {
			t.Fatal(err)
		}

		if got := readFile(t, fs, readmePath); strings.Contains(got, "OpenAPI") {
			t.Errorf("no API description, so no badge: %s", got)
		}
	})

	t.Run("a private repository still gets it", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, openAPIPath, validOpenAPI)

		if err := generateReadme(fs, "user", "gorepo", true, 96.4); err != nil {
			t.Fatal(err)
		}

		if got := readFile(t, fs, readmePath); !strings.Contains(got, "badge/OpenAPI-3.1.0-blue") {
			t.Errorf("missing the OpenAPI badge: %s", got)
		}
	})

	// An invalid description is a problem worth stopping for, rather than a
	// badge quietly left off.
	t.Run("an invalid document fails the task", func(t *testing.T) {
		for _, tc := range []struct {
			name, doc string
		}{
			{"no info block", `{"openapi": "3.1.0", "paths": {}}`},
			{"no specification version", `{"info": {"title": "T", "version": "1"}}`},
			{"not a version at all", `{"openapi": "nope", "info": {"title": "T", "version": "1"}}`},
			{"nothing in it", `{"openapi": "3.1.0", "info": {"title": "T", "version": "1"}}`},
			{"malformed JSON", `{"openapi":`},
		} {
			t.Run(tc.name, func(t *testing.T) {
				fs := afero.NewMemMapFs()
				writeFile(t, fs, openAPIPath, tc.doc)

				err := generateReadme(fs, "user", "gorepo", false, 96.4)
				if err == nil {
					t.Fatal("expected an error for an invalid API description, got nil")
				}

				if !strings.Contains(err.Error(), openAPIPath) {
					t.Errorf("error does not name the file: %v", err)
				}
			})
		}
	})
}

// TestGenerateReadmeLinksConventionalDocs covers the reading half: which of
// the conventional documents a repository has. What the footer then looks
// like is the golden files' business.
func TestGenerateReadmeLinksConventionalDocs(t *testing.T) {
	t.Run("only the documents that exist are linked", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "README/description.md", "A blurb.\n")
		writeFile(t, fs, "docs/architecture.md", "# Architecture\n")

		if err := generateReadme(fs, "user", "gorepo", false, 96.4); err != nil {
			t.Fatal(err)
		}

		got := readFile(t, fs, readmePath)

		if !strings.Contains(got, "[**Architecture**](docs/architecture.md)") {
			t.Errorf("missing the link to the document that is there:\n%s", got)
		}

		// A link to a file that is not there would be worse than no link.
		if strings.Contains(got, "docs/roadmap.md") {
			t.Errorf("linked a document this repository does not have:\n%s", got)
		}
	})

	t.Run("a repository with neither gets no section", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "README/description.md", "A blurb.\n")

		// Private, so the footer's other section is out of the way and the
		// absence being tested is the documents'.
		if err := generateReadme(fs, "user", "gorepo", true, 96.4); err != nil {
			t.Fatal(err)
		}

		if got := readFile(t, fs, readmePath); strings.Contains(got, "Additional Information") {
			t.Errorf("nothing to put in it, so no section:\n%s", got)
		}
	})

	// The reason these are linked at all: a private repository has no
	// pkg.go.dev page, so its own documents are most of what there is.
	t.Run("a private repository gets them", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "README/description.md", "A blurb.\n")
		writeFile(t, fs, "docs/architecture.md", "# Architecture\n")
		writeFile(t, fs, "docs/roadmap.md", "# Roadmap\n")

		if err := generateReadme(fs, "user", "gorepo", true, 96.4); err != nil {
			t.Fatal(err)
		}

		got := readFile(t, fs, readmePath)

		checkOrder(t, got, []string{
			"## Additional Information",
			"[**Architecture**](docs/architecture.md)",
			"[**Roadmap**](docs/roadmap.md)",
		})

		// And still none of the footer that needs an audience.
		for _, unwanted := range []string{"Go Reference", "## Contributing", "## License"} {
			if strings.Contains(got, unwanted) {
				t.Errorf("a private repository should not get %q:\n%s", unwanted, got)
			}
		}
	})

	t.Run("a directory at one of those paths is passed over", func(t *testing.T) {
		fs := afero.NewMemMapFs()
		writeFile(t, fs, "README/description.md", "A blurb.\n")

		if err := fs.MkdirAll("docs/roadmap.md", 0o755); err != nil {
			t.Fatal(err)
		}

		if err := generateReadme(fs, "user", "gorepo", false, 96.4); err != nil {
			t.Fatal(err)
		}

		if got := readFile(t, fs, readmePath); strings.Contains(got, "docs/roadmap.md") {
			t.Errorf("a directory is not a document to link:\n%s", got)
		}
	})
}

// TestGenerateReadmeTwiceDoesNotAdoptItsOwnOutput reproduces what two
// scheduled runs did to a repository with nothing to say: the first wrote a
// README carrying only the stamp and the badge row and no fragment to go with
// it, and the second adopted that as though a human had written it — folding
// the stamp and the badges into README/description.md and rendering them
// inside the next README, which then carried the stamp twice.
func TestGenerateReadmeTwiceDoesNotAdoptItsOwnOutput(t *testing.T) {
	fs := afero.NewMemMapFs()

	for range 2 {
		if err := generateReadme(fs, "MarkRosemaker", "patchpal", false, 34); err != nil {
			t.Fatal(err)
		}
	}

	got := readFile(t, fs, readmePath)

	if n := strings.Count(got, generatedMarker); n != 1 {
		t.Errorf("README.md carries the stamp %d times, want 1:\n%s", n, got)
	}

	// The fragment must not exist at all: there was nothing to adopt.
	if ok, err := afero.Exists(fs, filepath.Join(readmeDir, "description.md")); err != nil {
		t.Fatal(err)
	} else if ok {
		body := readFile(t, fs, filepath.Join(readmeDir, "description.md"))
		t.Errorf("a description fragment was invented from this task's own output:\n%s", body)
	}
}

// TestGenerateReadmeStillAdoptsAHandWrittenOne is the other half: the guard
// must not stop a real adoption.
func TestGenerateReadmeStillAdoptsAHandWrittenOne(t *testing.T) {
	fs := afero.NewMemMapFs()
	writeFile(t, fs, readmePath, "# thing\n\nSomething a person wrote.\n")

	if err := generateReadme(fs, "MarkRosemaker", "thing", false, 0); err != nil {
		t.Fatal(err)
	}

	if ok, err := afero.Exists(fs, readmeDir); err != nil {
		t.Fatal(err)
	} else if !ok {
		t.Fatal("a hand-written README was not adopted")
	}
}
